### ISSUE TITLE
 cordova-plugin-file not found when installing cordova-plugin-zip

### ISSUE THREAD

**Issue by ebrehault** [MobileChromeApps/cordova-plugin-zip#50]
The **org.apache.cordova.file** dependency recently changed to **cordova-plugin-file**, and now we get an error when cordova install cordova-plugin-zip, because cordova-plugin-file is not available on http://registry.cordova.io/ (as it is not released yet, see https://issues.apache.org/jira/browse/CB-8806).
It might also produce conflicts with other Apache plugins depending on org.apache.cordova.file (like like org.apache.cordova.file-transfer or org.apache.cordova.media).
I wrote an answer on stackoverflow about that: http://stackoverflow.com/questions/30302647/error-404-cordova-plugin-file-when-trying-to-install-cordova-plugin-zip-for-ios/30344258#30344258, but maybe it would be helpful to mention it on the README until org.apache.cordova.file v2 is released.

**Comment by agrieve** [comment]
Thanks for pointing this out!

I've fixed the README to not have people installing straight from git (you should generally install only from published versions on the registry)
